### ISSUE TITLE
[FEATURE] Footer links are not interactive.

### ISSUE THREAD

**Issue by tarunfy** [WebXDAO/WebXDAO.github.io#241]
### Detailed description

Once you hover over the links in the footer the cursor is default and they got no hover effect, I guess this is a bad UX, So there's a need to fix it, hence making our site much better with a little a improvement.

 

### Context

It will be a good UX. Hence enhancement to our site.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by void-ness** [comment]
Hey, It seems like they do have implemented something similar in the footer.
https://github.com/WebXDAO/WebXDAO.github.io/blob/16f9f4b9570f01d39ad5103216899b361f478f00/src/components/Global/Footer.js#L71-L76

However, the desired effect is not visible on the website due to a bug in code. You can check out the console box for the same. I also believe the styles needs to be applied on something else other than Link element and span element. Maybe you can look in that direction to fix it.

**Comment by tarunfy** [comment]
> Hey, It seems like they do have implemented something similar in the footer.
> 
> https://github.com/WebXDAO/WebXDAO.github.io/blob/16f9f4b9570f01d39ad5103216899b361f478f00/src/components/Global/Footer.js#L71-L76
> 
> However, the desired effect is not visible on the website due to a bug in code. You can check out the console box for the same. I also believe the styles needs to be applied on something else other than Link element and span element. Maybe you can look in that direction to fix it.

Hey Thanks for pointing it out, but anyways I fixed this and I'm creating a pr now.

**Comment by void-ness** [comment]
There's an error being logged into the console box due to footer. Can you fix that too?

**Comment by ItsRoy69** [comment]
Can I work on this ? If you assign it to me.

**Comment by vinzvinci** [comment]
tarunfy PR is merged https://github.com/WebXDAO/WebXDAO.github.io/pull/248. Closing this now!
