### ISSUE TITLE
[FEATURE] Projects Component

### ISSUE THREAD

**Issue by siddhantsingh186** [WebXDAO/WebXDAO.github.io#303]
### Detailed description

- [ ] Implement the Projects Section as per the new design.

### Context

New feature on the community website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by siddhantsingh186** [comment]
I would like to work on this issue.

**Comment by darkterminal** [comment]
Yeah... You can look at other issues first so that conflicts don't occur when pushes occur (my advice). You can choose which part you want to work on. But if you can work on it according to the new existing design, go ahead.

**Comment by siddhantsingh186** [comment]
Yes, I would like to proceed to work on this issue. Plz, assign me the issue.

**Comment by vinzvinci** [comment]
done @siddhantsingh186 ✔️

**Comment by siddhantsingh186** [comment]
Hey @vinzvinci . Can you explain how routes should be created for the navbar options? At the moment the routes are not working. We use /pages to create the routes, but they are nested inside /backup src. Also, the /backup src and /app are nested inside the same parent folder.

**Comment by darkterminal** [comment]
`backup src` is old source version. From now, we work in homepage before move to another pages.

**Comment by siddhantsingh186** [comment]
> `backup src` is old source version. From now, we work in homepage before move to another pages.

Yes but the navbar being used currently is of the older version . I am actually working on the projects page so I have to work on a new page basically, but the navbar link doesn't seem to work even if there is a projects.js in the pages file. Can you help me with this?

**Comment by mkubdev** [comment]
It's because navbar isn't synced automaticly with the app folder struct.
This app using nextjs 13 with the new app router, please see more here: https://nextjs.org/docs/app/building-your-application/routing

## Add an item into the navbar

Our navbar items is stored inside [config/site.ts](https://github.com/WebXDAO/WebXDAO.github.io/blob/87ad6dc826b598a23ad97f208c6b986fffc2ca68/config/site.ts#L6) file: 
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/50140834/6d510dfb-7642-4c53-8a89-7d671a6f9c38)

You can add an element in this array in order to show it inside the navbar.

---

> Yes but the navbar being used currently is of the older version

No, the actual navbar on the production server use the [`SiteHeader` component ](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/components/site-header.tsx) on `app/layout.tsx` : 
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/50140834/47e7ebee-72b7-4d07-8774-15c7223deae0)

## How to add a new page ?

As the navigation for projects is already implemetend (see screenshot above), to create a page please read carrefully how app routing work on next.js application: https://nextjs.org/docs/app/building-your-application/routing

But steps are:
1. create a `projects` folder
2. add a page.tsx 

And the projects page will work 🚀

**Comment by s2sharpit** [comment]
Hey, can I collaborate on this issue and help you with it?
